<?php



function pix_elementor_templates_content(){

    $thumbPath = 'https://wordpress.assets.pixfort.com/conseil/library/sections/content/';
    
    $templatesList = [

        ['demo_name' => 'Consulting', 'title' => 'About Levels', 'categories' => ['content', 'miscellaneous']],
        ['demo_name' => 'Consulting', 'title' => 'About Photo Stack Features', 'categories' => ['content', 'features']],
        ['demo_name' => 'Consulting', 'title' => 'Case Studies Content Left Photo Box', 'categories' => ['content', 'numbers']],
        ['demo_name' => 'Consulting', 'title' => 'Case Studies Projects Showcase', 'categories' => ['content', 'features']],
        ['demo_name' => 'Consulting', 'title' => 'Contact Form Map', 'categories' => ['content', 'maps', 'contact']],
        ['demo_name' => 'Consulting', 'title' => 'Features 3D Boxes', 'categories' => ['content', 'features']],
        ['demo_name' => 'Consulting', 'title' => 'Home Content Right Features', 'categories' => ['content', 'features']],
        ['demo_name' => 'Consulting', 'title' => 'Home Highlighted Box CTA', 'categories' => ['content', 'cta', 'features', 'numbers']],
        ['demo_name' => 'Consulting', 'title' => 'Services Cards', 'categories' => ['content', 'features']],
        ['demo_name' => 'Consulting', 'title' => 'Tab 1', 'categories' => ['content', 'features']],
        ['demo_name' => 'Consulting', 'title' => 'Tab 2', 'categories' => ['content', 'features']],
        ['demo_name' => 'Consulting', 'title' => 'Tab 3', 'categories' => ['content', 'features']],

        ['demo_name' => 'Digital Agency', 'title' => 'About Content Photo Stack Clients', 'categories' => ['content', 'clients']],
        ['demo_name' => 'Digital Agency', 'title' => 'About Content Review', 'categories' => ['content', 'reviews']],
        ['demo_name' => 'Digital Agency', 'title' => 'About Levels CTA', 'categories' => ['content', 'cta', 'miscellaneous']],
        ['demo_name' => 'Digital Agency', 'title' => 'Contact Form Review', 'categories' => ['content', 'contact', 'reviews']],
        ['demo_name' => 'Digital Agency', 'title' => 'Features Content Sticky', 'categories' => ['content', 'features']],
        ['demo_name' => 'Digital Agency', 'title' => 'Home Content Left Numbers', 'categories' => ['content', 'numbers']],
        ['demo_name' => 'Digital Agency', 'title' => 'Home Content Projects Cards', 'categories' => ['content']],
        ['demo_name' => 'Digital Agency', 'title' => 'Home Content Right Numbers', 'categories' => ['content', 'numbers']],
        ['demo_name' => 'Digital Agency', 'title' => 'Home Content Testimonial CTA Numbers', 'categories' => ['content', 'testimonials', 'cta', 'numbers']],
        ['demo_name' => 'Digital Agency', 'title' => 'Project Page Content Image Carousel', 'categories' => ['content', 'image_carousel']],
        ['demo_name' => 'Digital Agency', 'title' => 'Project Page Details', 'categories' => ['content']],
        ['demo_name' => 'Digital Agency', 'title' => 'Project Page Sticky Images', 'categories' => ['content']],
        ['demo_name' => 'Digital Agency', 'title' => 'Reviews Awards', 'categories' => ['content', 'reviews', 'miscellaneous']],
        ['demo_name' => 'Digital Agency', 'title' => 'Services Cards', 'categories' => ['content']],
        ['demo_name' => 'Digital Agency', 'title' => 'Services Content Steps', 'categories' => ['content']],
        ['demo_name' => 'Digital Agency', 'title' => 'Showcase Content Left Clients', 'categories' => ['content', 'clients']],

        ['demo_name' => 'Advisory', 'title' => 'About Content Heading Awards', 'categories' => ['content', 'headings']],
        ['demo_name' => 'Advisory', 'title' => 'About Content Text Review Testimonial Numbers', 'categories' => ['content', 'reviews', 'testimonials', 'numbers']],
        ['demo_name' => 'Advisory', 'title' => 'Careers Content Features Clients', 'categories' => ['content', 'features', 'clients']],
        ['demo_name' => 'Advisory', 'title' => 'Careers Jobs', 'categories' => ['content', 'miscellaneous']],
        ['demo_name' => 'Advisory', 'title' => 'Contact Information Content', 'categories' => ['content', 'contact']],
        ['demo_name' => 'Advisory', 'title' => 'Contact Information Map', 'categories' => ['content', 'maps', 'contact']],
        ['demo_name' => 'Advisory', 'title' => 'Features Sticky Content Sections', 'categories' => ['content', 'features']],
        ['demo_name' => 'Advisory', 'title' => 'Home Cards Wide Clients Marquee', 'categories' => ['content', 'clients', 'marquee']],
        ['demo_name' => 'Advisory', 'title' => 'Home Content Left', 'categories' => ['content']],
        ['demo_name' => 'Advisory', 'title' => 'Home Content Left Numbers', 'categories' => ['content', 'numbers']],
        ['demo_name' => 'Advisory', 'title' => 'Pricing Awards Rating', 'categories' => ['content', 'miscellaneous', 'reviews']],
        ['demo_name' => 'Advisory', 'title' => 'Reviews Content Numbers', 'categories' => ['content', 'reviews', 'numbers']],
        ['demo_name' => 'Advisory', 'title' => 'Services CTA Numbers Clients Marquee', 'categories' => ['content', 'cta', 'numbers', 'clients', 'marquee']],
        ['demo_name' => 'Advisory', 'title' => 'Services Sticky Content Images', 'categories' => ['content']],

        ['demo_name' => 'Growth', 'title' => 'Home Content Cards Features', 'categories' => ['content', 'features']],
        ['demo_name' => 'Growth', 'title' => 'Home Content Features', 'categories' => ['content', 'features']],
        ['demo_name' => 'Growth', 'title' => 'Home Content Marquee Vertical', 'categories' => ['content', 'marquee']],
        ['demo_name' => 'Growth', 'title' => 'About Content Awards', 'categories' => ['content', 'miscellaneous']],
        ['demo_name' => 'Growth', 'title' => 'About Content Left Features', 'categories' => ['content', 'features']],
        ['demo_name' => 'Growth', 'title' => 'About Content Right Video', 'categories' => ['content', 'video']],
        ['demo_name' => 'Growth', 'title' => 'Careers Jobs', 'categories' => ['content', 'miscellaneous']],
        ['demo_name' => 'Growth', 'title' => 'Contact Form', 'categories' => ['content', 'contact']],
        ['demo_name' => 'Growth', 'title' => 'Contact Information', 'categories' => ['content', 'contact']],
        ['demo_name' => 'Growth', 'title' => 'Contact Information Map', 'categories' => ['content', 'maps', 'contact']],
        ['demo_name' => 'Growth', 'title' => 'Features Cards Sticky Content', 'categories' => ['content', 'features']],
        ['demo_name' => 'Growth', 'title' => 'Services Clients', 'categories' => ['content', 'clients', 'cta']],
        ['demo_name' => 'Growth', 'title' => 'Services Content Cards Features', 'categories' => ['content', 'features']],
        ['demo_name' => 'Growth', 'title' => 'Services Content Left Features', 'categories' => ['content', 'features']],
        ['demo_name' => 'Growth', 'title' => 'Services Content Right Review Testimonial', 'categories' => ['content', 'reviews', 'testimonials']],
        ['demo_name' => 'Growth', 'title' => 'Tab 1', 'categories' => ['content', 'features', 'video']],
        ['demo_name' => 'Growth', 'title' => 'Tab 2', 'categories' => ['content', 'features']],
        ['demo_name' => 'Growth', 'title' => 'Tab 3', 'categories' => ['content', 'features']],
        ['demo_name' => 'Growth', 'title' => 'Tab 4', 'categories' => ['content', 'features']],

        ['demo_name' => 'Vision', 'title' => 'Home Content Boxes Features', 'categories' => ['content', 'features']],
        ['demo_name' => 'Vision', 'title' => 'Home Content Feature Boxes', 'categories' => ['content', 'features']],
        ['demo_name' => 'Vision', 'title' => 'Home Content Left Testimonial', 'categories' => ['content', 'testimonials']],
        ['demo_name' => 'Vision', 'title' => 'Home Content Numbers Testimonial Review Features CTA', 'categories' => ['content', 'numbers', 'testimonials', 'reviews', 'features', 'cta']],
        ['demo_name' => 'Vision', 'title' => 'Pricing Content Award Ratings Reviews', 'categories' => ['content', 'pricing', 'reviews', 'miscellaneous']],
        ['demo_name' => 'Vision', 'title' => 'Product Content Card Wide Features', 'categories' => ['content', 'features']],
        ['demo_name' => 'Vision', 'title' => 'Product Content Left', 'categories' => ['content']],
        ['demo_name' => 'Vision', 'title' => 'Product Content Right', 'categories' => ['content']],
        ['demo_name' => 'Vision', 'title' => 'Product Content Video Clients', 'categories' => ['content', 'video', 'clients']],
        ['demo_name' => 'Vision', 'title' => 'Services Sticky Content Sections Features', 'categories' => ['content', 'features']],
        ['demo_name' => 'Vision', 'title' => 'Contact Information Map', 'categories' => ['content', 'maps', 'contact']],

        ['demo_name' => 'Partners', 'title' => 'Home Content Left', 'categories' => ['content']],
        ['demo_name' => 'Partners', 'title' => 'Home Content Right', 'categories' => ['content']],
        ['demo_name' => 'Partners', 'title' => 'Home Content Numbers CTA', 'categories' => ['content', 'numbers', 'cta']],
        ['demo_name' => 'Partners', 'title' => 'Services Awards', 'categories' => ['content', 'miscellaneous']],
        ['demo_name' => 'Partners', 'title' => 'Services Content Cards', 'categories' => ['content']],
        ['demo_name' => 'Partners', 'title' => 'Services Content Cards Features', 'categories' => ['content', 'features']],
        ['demo_name' => 'Partners', 'title' => 'Services Content Features Numbers', 'categories' => ['content', 'features', 'numbers']],
        ['demo_name' => 'Partners', 'title' => 'Services Content Steps', 'categories' => ['content', 'miscellaneous']],
        ['demo_name' => 'Partners', 'title' => 'About Cards Sticky Content', 'categories' => ['content', 'features']],
        ['demo_name' => 'Partners', 'title' => 'Careers Awards', 'categories' => ['content', 'miscellaneous']],
        ['demo_name' => 'Partners', 'title' => 'Careers Content Features List Rating Award', 'categories' => ['content', 'features', 'reviews', 'miscellaneous']],
        ['demo_name' => 'Partners', 'title' => 'Careers Jobs Content', 'categories' => ['content', 'miscellaneous']],
        ['demo_name' => 'Partners', 'title' => 'Contact Form Information Map Links', 'categories' => ['content', 'maps', 'contact', 'links']],

        ['demo_name' => 'Prime', 'title' => 'Cards Sticky Content', 'categories' => ['content', 'features']],
        ['demo_name' => 'Prime', 'title' => 'Contact Information Map', 'categories' => ['content', 'maps', 'contact']],
        ['demo_name' => 'Prime', 'title' => 'Content Left Charts', 'categories' => ['content', 'miscellaneous', 'charts']],
        ['demo_name' => 'Prime', 'title' => 'Content Right Features', 'categories' => ['content', 'features']],

        ['demo_name' => 'Trust', 'title' => 'Home Content Left Video Features', 'categories' => ['content', 'video', 'features']],
        ['demo_name' => 'Trust', 'title' => 'Home Content Right', 'categories' => ['content']],
        ['demo_name' => 'Trust', 'title' => 'Home Sticky Scale Content', 'categories' => ['content']],
        ['demo_name' => 'Trust', 'title' => 'Solutions Content Features Progress Bars', 'categories' => ['content', 'features', 'miscellaneous', 'charts']],
        ['demo_name' => 'Trust', 'title' => 'Solutions Content Left', 'categories' => ['content']],
        ['demo_name' => 'Trust', 'title' => 'Services Content Boxes Marquee', 'categories' => ['content', 'marquee']],
        ['demo_name' => 'Trust', 'title' => 'Services Content Features Grid', 'categories' => ['content', 'features']],
        ['demo_name' => 'Trust', 'title' => 'Services Sticky Content Fancy Boxes', 'categories' => ['content', 'features']],
        ['demo_name' => 'Trust', 'title' => 'Contact Form', 'categories' => ['content', 'contact']],
        ['demo_name' => 'Trust', 'title' => 'Contact Information Map', 'categories' => ['content', 'maps', 'contact']],

        ['demo_name' => 'RTL', 'title' => 'Home Content Cards Features', 'categories' => ['content', 'features']],
        ['demo_name' => 'RTL', 'title' => 'Home Content Features', 'categories' => ['content', 'features']],
        ['demo_name' => 'RTL', 'title' => 'Home Content Marquee Vertical', 'categories' => ['content', 'marquee']],
        ['demo_name' => 'RTL', 'title' => 'Services Clients', 'categories' => ['content', 'clients', 'cta']],
        ['demo_name' => 'RTL', 'title' => 'Services Content Cards Features', 'categories' => ['content', 'features']],
        ['demo_name' => 'RTL', 'title' => 'Services Content Left Features', 'categories' => ['content', 'features']],
        ['demo_name' => 'RTL', 'title' => 'Services Content Right Review Testimonial', 'categories' => ['content', 'reviews', 'testimonials']],
        ['demo_name' => 'RTL', 'title' => 'Features Cards Sticky Content', 'categories' => ['content', 'features']],
        ['demo_name' => 'RTL', 'title' => 'Careers Jobs', 'categories' => ['content', 'miscellaneous']],
        ['demo_name' => 'RTL', 'title' => 'About Content Awards', 'categories' => ['content', 'miscellaneous']],
        ['demo_name' => 'RTL', 'title' => 'About Content Left Features', 'categories' => ['content', 'features']],
        ['demo_name' => 'RTL', 'title' => 'About Content Right Video', 'categories' => ['content', 'video']],
        ['demo_name' => 'RTL', 'title' => 'Contact Form', 'categories' => ['content', 'contact']],
        ['demo_name' => 'RTL', 'title' => 'Contact Information', 'categories' => ['content', 'contact']],
        ['demo_name' => 'RTL', 'title' => 'Contact Information Map', 'categories' => ['content', 'maps', 'contact']],
        ['demo_name' => 'RTL', 'title' => 'Tab 1', 'categories' => ['content', 'features', 'video']],
        ['demo_name' => 'RTL', 'title' => 'Tab 2', 'categories' => ['content', 'features']],
        ['demo_name' => 'RTL', 'title' => 'Tab 3', 'categories' => ['content', 'features']],
        ['demo_name' => 'RTL', 'title' => 'Tab 4', 'categories' => ['content', 'features']],

        ['demo_name' => 'App', 'title' => 'Home Content Features Carousel CTA', 'categories' => ['content', 'features', 'cta', 'image_carousel']],
        ['demo_name' => 'App', 'title' => 'Home Feature Content Left', 'categories' => ['content', 'features']],
        ['demo_name' => 'App', 'title' => 'Home Feature Content Right', 'categories' => ['content', 'features']],
        ['demo_name' => 'App', 'title' => 'Home Feature Content Left 2', 'categories' => ['content', 'features']],

        ['demo_name' => 'SaaS', 'title' => 'Contact Form Map', 'categories' => ['content', 'maps', 'contact']],
        ['demo_name' => 'SaaS', 'title' => 'Contact Information', 'categories' => ['content', 'contact']],
        ['demo_name' => 'SaaS', 'title' => 'Services Steps', 'categories' => ['content', 'miscellaneous']],
        ['demo_name' => 'SaaS', 'title' => 'Changelog New Version Update Entry 2', 'categories' => ['content', 'miscellaneous']],
        ['demo_name' => 'SaaS', 'title' => 'Singe Service Related Services', 'categories' => ['content', 'features']],
        ['demo_name' => 'SaaS', 'title' => 'Services Grid', 'categories' => ['content', 'features']],
        ['demo_name' => 'SaaS', 'title' => 'Services Feature Boxes Scale In', 'categories' => ['content', 'features']],
        ['demo_name' => 'SaaS', 'title' => 'Changelog New Version Update Entry 1', 'categories' => ['content', 'miscellaneous']],
        ['demo_name' => 'SaaS', 'title' => 'Product Content Features CTA', 'categories' => ['content', 'features', 'cta']],
        ['demo_name' => 'SaaS', 'title' => 'Product Content Left 1', 'categories' => ['content']],
        ['demo_name' => 'SaaS', 'title' => 'Product Content Left 2', 'categories' => ['content']],
        ['demo_name' => 'SaaS', 'title' => 'Product Content Right', 'categories' => ['content']],
        ['demo_name' => 'SaaS', 'title' => 'Home Sticky Content Left Features', 'categories' => ['content', 'features']],
        ['demo_name' => 'SaaS', 'title' => 'Home Image Showcase', 'categories' => ['content', 'miscellaneous']],

    ];

    return pix_generate_templates($templatesList, 'content', $thumbPath);
}




 ?>
